### PR TITLE
Implemented endianness switch

### LINKED ISSUE #15: Add switch to toggle endianness
Right now multi-byte values are show as little-endian integers, it would be great to also support big-endian.

### PR DESCRIPTION
**Pull request by JungleTryne**
Fixes #15
Now with `CTRL+e` one can switch endianness in the editor. The notification about it will pop up once the user uses the hotkey

### CODE REVIEW

**Comment by ndd7xv** [comment]
Thanks so much for the PR! This is especially nice since the issue was created externally :D 

I'll try and review it in the coming days :)

**Comment by ndd7xv** [comment]
This looks great! I'm thinking that in the future, I'll find some way to refactor the entire label file, but currently don't how else endianness would be implemented  with how label.rs it exists now (sorry about the messiness).

One nitpick - would it be OK if we changed the `format` statements as suggested by clippy?

https://github.com/ndd7xv/heh/actions/runs/4622352159/jobs/8198035205#step:4:210

**Comment by JungleTryne** [comment]
Sure thing! I've fixed it, now clippy shouldn't generate those errors

**Comment by ndd7xv** [comment]
Thanks so much! Merging now :)

**Pull request merged**
