### PR TITLE
Implement scroll feature

### LINKED ISSUE #6: Implement Scroll Feature
Scrolling with the mouse should move the view up and down, similar to when moving the cursor outside the current view of bytes.

### PR DESCRIPTION
**Pull request by yuankunzhang**
Support mouse scrolling up and down.

Closes #6

### CODE REVIEW

**Comment by ndd7xv** [comment]
Hi, thank you so much for the PR! It's very obvious you know what you're doing - I think if anything I could take notes off of what you have done, and I greatly appreciate the comments and refactoring!

One nitpick I have is that scrolling up and down currently also moves the cursor. I think editors usually keep your cursor in the same position when you scroll, which makes it easier to quickly check something in a different location of the file and then edit at the initial position. 

In the near future, I hope to implement clicks to move the cursor, as well as https://github.com/ndd7xv/heh/issues/3 so people can move their cursor after scrolling. But for now, would it be OK to tweak your PR so that scrolling only changes `start_address` by `bytes_per_line`? If you don't have time to do that, I can go ahead and merge, but I might tweak the functionatliy in the future so that the scrolling doesn't change the cursor position.

**Comment by yuankunzhang** [comment]
Hi, thanks for the prompt response. Your idea very much makes sense, I'll make a change soon.

**Comment by yuankunzhang** [comment]
I've updated the code to scroll without changing the cursor.

**Review by ndd7xv — APPROVED** [review]

**Comment by ndd7xv** [comment]
Thanks for the changes and the refactor! I very much appreciate it, the code is definitely more understandable now :smile:

**Comment by yuankunzhang** [comment]
Thanks for starting the project, and looking to see it grows!

**Pull request merged**
